### PR TITLE
Fix scenario FC108

### PR DESCRIPTION
**Pull request by mentonin**
This is related to #50 but does not solve it. Removes the note from section FC37 and adds allies for sections FC37 and FC44.

### CODE REVIEW

**Comment by Tarmslitaren** [comment]
Have you checked that this actually works?
i.e: when the monster types are added, they be added as allies, which in practice means 2 things: 1. the ally deck becomes visible and 2, when adding curses or blesses from the monsters status menus they end up in the ally deck.
This is actually also one of the Frosthaven changes, that could be optional, since Gloomhaven does not have a n ally deck.

**Comment by mentonin** [comment]
> Have you checked that this actually works?
> i.e: when the monster types are added, they be added as allies, which in practice means 2 things: 1. the ally deck becomes visible and 2, when adding curses or blesses from the monsters status menus they end up in the ally deck.
> This is actually also one of the Frosthaven changes, that could be optional, since Gloomhaven does not have a n ally deck.

I actually haven't done testing on it, but that is the behaviour I expected. Other missions outside FH already have implemented the allies rule, so I figured it only made sense. I actually thought of doing it for section FC101 as well, which would be thematically much nicer (and just tell the user to use allies deck for one of the armies).

The idea would be to make it an optional house rule anyway, right? And in the future, if ally monsters are now painted blue instead of red or something like that, this also helps even if the house rule is turned off.

**Comment by Tarmslitaren** [comment]
Might be best to add a set as ally on the created monster type, however there's no optimal place for it. The ability card menu is probably best, but it's not the logical place. the status menu is already too busy to add much more stuff. 

An alternative is to scrap adding curses and blesses from status menu and only have that functionality from the attack modifier deck menues

**Comment by mentonin** [comment]
Implemented the section idea. I couldn't implement the note on section opening just from metadata, though. I didn't delve into the code to see if it is possible, but it seems to me it isn't. I think we should implement that, especially because we can do things like display errata (#55).

**Comment by Tarmslitaren** [comment]
You should add the note about adding sections as a timer, with startOfTurn: true and list:[1] to show at start of turn one.

I believe The note about bosses using same deck is superfluous? This is how all scenarios with several bosses work. Either the app needs to implement drawing twice from the same deck, or leave it as is with 2 unique boss decks as a 'good enough' approximation. A note will only confuse.

**Comment by mentonin** [comment]
> You should add the note about adding sections as a timer, with startOfTurn: true and list:[1] to show at start of turn one.

I tried that, but it only shows the banner when drawing initiative cards. The note should be shown when setting the scenario instead.

> I believe The note about bosses using same deck is superfluous? This is how all scenarios with several bosses work. Either the app needs to implement drawing twice from the same deck, or leave it as is with 2 unique boss decks as a 'good enough' approximation. A note will only confuse.

The note was already there, this PR removes it.

**Comment by Tarmslitaren** [comment]
Sorry I misread the diff :)

I've added support for showing message on start scenario / add section with "initialMessage" string in scenario json object. Should be enough to deal with this and #55.

**Comment by Tarmslitaren** [comment]
Changes added in main during section per scenario change. closing

**Pull request closed without merging**
