### PR TITLE
Remove sockets from client

### PR DESCRIPTION
**Pull request by wonderplayer**
So, this is my first attempt on refactoring client, and this is what I'm planning to do with server.
Their needs are similar, but functionality is different. Sending and receiving data is the same, so they shouldn't know how many sockets to communicate to, or even know that there is such things as sockets. It will be easier to change communication protocol later on.
I'm thinking in the end to get to gRPC (wanted to try them long ago :D) so it will simplify listening, as you won't need to listen, you only call remote procedures over network and receive response.

What do you think? It will make client and server more testable, but not quite yet. After server, I will unload action handler, as it also tries to take different actions depending on whether current app is server or client. This creates huge complexity in testing. I'm planning to go with command approach (define message interfaces) and then abstract from current action implementation. Define it in respective handlers - for server and for client - and action handler might only need to say that command should be executed, and app by itself will decide who should execute it and by which rules.

### CODE REVIEW

**Comment by Tarmslitaren** [comment]
sounds promising. One major reason for using tcp to begin with is higher speeds on local network as compared to a server based approach. I dont know enough about gRPC tp say if that can wholly replace local tcp/ip or if it would be as an alternative.

would you like me to merge? I assume you have tested that everything still works 😅

**Comment by wonderplayer** [comment]
I’ve tested that client receives messages, processes them, sends messages and is able to disconnect properly, and show errors. I hope I tested everything 😅
Maybe you can merge in some other branch? At least you won’t lose your work and will be able to test when you are able to. But should be fine - not a huge change 😄

**Comment by wonderplayer** [comment]
I don’t know much myself about gRPC, that’s why I want to try it out 😁
[Here](https://www.infoq.com/articles/websocket-and-http2-coexist/) is a nice article I stumbled upon.

**Comment by Tarmslitaren** [comment]
Ill trust it works, Worst case I can always revert.

**Pull request merged**
